### ISSUE TITLE
Can't unstash tabs anymore

### ISSUE THREAD

**Issue by junkblocker** [josh-berry/tab-stash#26] opened 2019-06-26 14:04 UTC
**Describe the bug**
See attached gif. Stash works but unstash is completely broken suddenly. Don't see any exceptions in the console log. I had installed Temporary Containers recently and it was working after that but suddenly, even after disabling that, restarting the browser etc. it is not working.

**To Reproduce**
Detailed steps to reproduce the behavior:

**Expected behavior**

**Screenshots**
https://gyazo.com/b7dbd2aeee76533f4efa0c725966cb41

**Desktop (please complete the following information):**
 - OS: macOS
 - Firefox Browser Version: 67.0.4

**Additional context**
The only remaining way for me to open it is via the firefox right click menu > "Open Link in New Tab" etc.

**Comment by josh-berry** [comment] 2019-06-26 16:24
Thanks for the screen capture, and sorry for the trouble! That certainly should not be happening.

When you checked the console, were you looking at the normal website console log? Sidebar issues won't necessarily show up there—you have to dig around in `about:debugging` to get to the extensions console, which should show the errors:

1. Go to `about:debugging`
2. Turn on "Enable add-on debugging"
3. Click "Debug" for the Tab Stash extension
4. This will open a separate window with the JavaScript console. (Note that it may show internal errors from the browser itself in addition to any Tab Stash errors.)

Alternatively, can you try to reproduce the problem with the tab view instead of the sidebar view? The console log for the tab view should show any exceptions that are happening.

**Comment by junkblocker** [comment] 2019-06-26 16:51
Thought I had addon debugging enabled, but anyway, here's what I see.

```
Error in parsing value for ‘will-change’.  Declaration dropped. stash-list.html
Error: "An unexpected error occurred"
```

**Comment by josh-berry** [comment] 2019-06-26 17:05
hm okay. This looks like a CSS error that shouldn't be affecting your ability to restore tabs. Let me dig a little more and see if there are any code paths where we can silently fail in this fashion. (There shouldn't be, but it's always possible I've missed something.)

**Comment by junkblocker** [comment] 2019-06-26 19:23
1. The CSS error has disappeared but I am still getting the

```
Error: "An unexpected error occurred"
```

2. Middle click works ok.

**Comment by josh-berry** [comment] 2019-06-27 01:58
A few more questions:
1. Is it just this one tab, or is it every tab in the stash that is failing to open?
2. If it's just this one tab, is it a Reader Mode tab or a regular website, and would you be comfortable sharing the URL that's saved in the stash/your bookmarks? (Totally okay if not, but might help me reproduce the problem.)
3. Are any of the problematic tabs open anywhere else in Firefox (e.g. another window)?
4. Do any of the problematic tabs appear in your list of recently closed tabs? ("History" menu > "Recently Closed Tabs")
5. What happens when you try to restore an entire group of tabs at once (using the green "Open all tabs..." button underneath the stash name)?

The "unexpected error occurred" message is not something Tab Stash itself will ever produce, nor any of its library dependencies as far as I can tell. That suggests something internal to the browser is failing, but I'm not sure yet why that would be—hopefully the above questions will help narrow it down.

**Comment by junkblocker** [comment] 2019-06-27 02:33
1. Every tab is failing to open.
2. No, I don't user reader mode. Nothins special about any urls - here's one https://news.ycombinator.com/item?id=8830903
3. No.
4. No.
5. Doesn't work.

Q5 reminded me, I had attempted to open a large group of tabs and had to force quit the browser because it semi froze so likely some firefox state is corrupted somewhere :( . I don't want to "Refresh Firefox..." if I can avoid it but seems may not have another choice.

**Comment by josh-berry** [comment] 2019-06-27 02:58
Given that it's just with restoring tabs and stashing works OK, one thing you could try is clear the "Restore previous session" setting in Preferences, restart the browser, and see if that helps. If the problem is just with the session state and not with any of your other bookmarks/settings/etc. you might not have to do a full refresh.

**Comment by junkblocker** [comment] 2019-06-27 03:05
That did work! Thanks!

**Comment by josh-berry** [comment] 2019-06-27 03:08
Awesome, glad to hear it! I'll chalk it up to browser bugs and close this out, but feel free to re-open (or open a new issue) if you run into trouble again.

**Closed by josh-berry** 2019-06-27 03:08 UTC
Labels: support request
