### ISSUE TITLE
tab stash has stopped working

### ISSUE THREAD

**Issue by selster** [josh-berry/tab-stash#45] opened 2020-02-14 18:40 UTC
specifically the feature that will copy all stashed tabs to one web page.  I have tried removing and re-enabling tab stash, no effect?  Can you help with this?  Win 7 64 bit using the latest firefox
Thanks, Steve

### Steps to Reproduce
*Detailed steps to reproduce the problem:*

### Expected Behavior
*A clear and concise description of what you expected to happen.*

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### Desktop (please complete the following information):
 - **OS:**
 - **Firefox Browser Version:** *[e.g. 60.0.2]*

**Comment by josh-berry** [comment] 2020-02-15 06:02
Hi Steve, I'm afraid I haven't been able to reproduce this on my end, can you share exactly what steps you were trying?

Have you seen any other issues apart from tab copying?

Thanks,
Josh

**Comment by selster** [comment] 2020-02-15 06:07
Your tool is magnificent. It does many things. One of them, I can click on an option that says put all of my tabs on one webpage, in a separate tab. all I can tell you is that this no longer works. I have no idea why. I did recently notice that Firefox had begun to use six gigs of RAM after I had installed some other add-ins. Now that I have removed them, it's gone back to its normal, say 240 for instance the Firefox. I'll have to try again and see if the removal of those other add-ins has had a soluatory effect on yours.  If I knew how to turn out a debugger, I could watch it. But I don't. Do you




Get Outlook for Android







On Fri, Feb 14, 2020 at 10:02 PM -0800, "Josh Berry" <notifications@github.com> wrote:












Hi Steve, I'm afraid I haven't been able to reproduce this on my end, can you share exactly what steps you were trying?


Have you seen any other issues apart from tab copying?


Thanks,

Josh

**Comment by josh-berry** [comment] 2020-02-16 08:09
Ahh okay, I misunderstood. A couple quick things to (double-)check:

1. Right-click on the Tab Stash icon in your toolbar, and choose "Show Stashed Tabs in a Tab". Does this open the Tab Stash page for you as you would expect?
2. Right-click on the Tab Stash icon in your toolbar, and choose "Manage Extension". This will open the add-on settings for Tab Stash. Then click on "Options", and check if "Automatically show your stashed tabs in a new tab" is selected. If you select it, does this bring back the behavior you were looking for?

If neither 1 or 2 work for you, here's how you can collect debugging info:

1. Open a new tab and go to `about:debugging`.
2. Choose "This Firefox" in the sidebar
3. Find Tab Stash in the list of add-ons and click "Inspect". This should open the Firefox developer tools.
4. Click on the "Console" tab in the developer tools to see log messages and such.
5. Try to reproduce the problem you were seeing before.

NOTE: Logs for some internal browser things show up here as well, so even if you see errors, it's not necessarily indicative of a problem with Tab Stash. You can paste the log here if you want help interpreting it, or if you want to dig deeper yourself, the easiest way to sort out which messages are relevant is to look for messages from "index.js", "stash-list.js" or "options.js".

Hope this helps!

**Comment by selster** [comment] 2020-02-16 08:12
Show Stashed Tabs in a Tab




This is what it stopped working, it's a great feature, can the above page, does the above page has its own URL that I can send to someone else?  I will try the above




Get Outlook for Android







On Sun, Feb 16, 2020 at 12:09 AM -0800, "Josh Berry" <notifications@github.com> wrote:












Ahh okay, I misunderstood. A couple quick things to (double-)check:

Right-click on the Tab Stash icon in your toolbar, and choose "Show Stashed Tabs in a Tab". Does this open the Tab Stash page for you as you would expect?
Right-click on the Tab Stash icon in your toolbar, and choose "Manage Extension". This will open the add-on settings for Tab Stash. Then click on "Options", and check if "Automatically show your stashed tabs in a new tab" is selected. If you select it, does this bring back the behavior you were looking for?



If neither 1 or 2 work for you, here's how you can collect debugging info:

Open a new tab and go to about:debugging.
Choose "This Firefox" in the sidebar
Find Tab Stash in the list of add-ons and click "Inspect". This should open the Firefox developer tools.
Click on the "Console" tab in the developer tools to see log messages and such.
Try to reproduce the problem you were seeing before.



NOTE: Logs for some internal browser things show up here as well, so even if you see errors, it's not necessarily indicative of a problem with Tab Stash. You can paste the log here if you want help interpreting it, or if you want to dig deeper yourself, the easiest way to sort out which messages are relevant is to look for messages from "index.js", "stash-list.js" or "options.js".


Hope this helps!

**Comment by selster** [comment] 2020-02-16 08:12
Yesterday I was trying to send my tabs to someone else, when suddenly this feature stopped working




On Sun, Feb 16, 2020 at 12:09 AM -0800, "Josh Berry" <notifications@github.com> wrote:












Ahh okay, I misunderstood. A couple quick things to (double-)check:

Right-click on the Tab Stash icon in your toolbar, and choose "Show Stashed Tabs in a Tab". Does this open the Tab Stash page for you as you would expect?
Right-click on the Tab Stash icon in your toolbar, and choose "Manage Extension". This will open the add-on settings for Tab Stash. Then click on "Options", and check if "Automatically show your stashed tabs in a new tab" is selected. If you select it, does this bring back the behavior you were looking for?



If neither 1 or 2 work for you, here's how you can collect debugging info:

Open a new tab and go to about:debugging.
Choose "This Firefox" in the sidebar
Find Tab Stash in the list of add-ons and click "Inspect". This should open the Firefox developer tools.
Click on the "Console" tab in the developer tools to see log messages and such.
Try to reproduce the problem you were seeing before.



NOTE: Logs for some internal browser things show up here as well, so even if you see errors, it's not necessarily indicative of a problem with Tab Stash. You can paste the log here if you want help interpreting it, or if you want to dig deeper yourself, the easiest way to sort out which messages are relevant is to look for messages from "index.js", "stash-list.js" or "options.js".


Hope this helps!

**Comment by selster** [comment] 2020-02-16 08:13
IfShow Stashed Tabs in a Tab


Created its own URL, then I could send all my tabs in there stashes to someone else, wouldn't that be cool






On Sun, Feb 16, 2020 at 12:09 AM -0800, "Josh Berry" <notifications@github.com> wrote:












Ahh okay, I misunderstood. A couple quick things to (double-)check:

Right-click on the Tab Stash icon in your toolbar, and choose "Show Stashed Tabs in a Tab". Does this open the Tab Stash page for you as you would expect?
Right-click on the Tab Stash icon in your toolbar, and choose "Manage Extension". This will open the add-on settings for Tab Stash. Then click on "Options", and check if "Automatically show your stashed tabs in a new tab" is selected. If you select it, does this bring back the behavior you were looking for?



If neither 1 or 2 work for you, here's how you can collect debugging info:

Open a new tab and go to about:debugging.
Choose "This Firefox" in the sidebar
Find Tab Stash in the list of add-ons and click "Inspect". This should open the Firefox developer tools.
Click on the "Console" tab in the developer tools to see log messages and such.
Try to reproduce the problem you were seeing before.



NOTE: Logs for some internal browser things show up here as well, so even if you see errors, it's not necessarily indicative of a problem with Tab Stash. You can paste the log here if you want help interpreting it, or if you want to dig deeper yourself, the easiest way to sort out which messages are relevant is to look for messages from "index.js", "stash-list.js" or "options.js".


Hope this helps!

**Comment by selster** [comment] 2020-02-16 08:15
I eventually figured away around it but it meant uploading several hundred PDFs to Dropbox and then asking my colleague to to download from there, it would have been much more efficient if I could have just waited for your program to generate a The page with all my tabs and their stashes, and then sent him the URL






On Sun, Feb 16, 2020 at 12:09 AM -0800, "Josh Berry" <notifications@github.com> wrote:












Ahh okay, I misunderstood. A couple quick things to (double-)check:

Right-click on the Tab Stash icon in your toolbar, and choose "Show Stashed Tabs in a Tab". Does this open the Tab Stash page for you as you would expect?
Right-click on the Tab Stash icon in your toolbar, and choose "Manage Extension". This will open the add-on settings for Tab Stash. Then click on "Options", and check if "Automatically show your stashed tabs in a new tab" is selected. If you select it, does this bring back the behavior you were looking for?



If neither 1 or 2 work for you, here's how you can collect debugging info:

Open a new tab and go to about:debugging.
Choose "This Firefox" in the sidebar
Find Tab Stash in the list of add-ons and click "Inspect". This should open the Firefox developer tools.
Click on the "Console" tab in the developer tools to see log messages and such.
Try to reproduce the problem you were seeing before.



NOTE: Logs for some internal browser things show up here as well, so even if you see errors, it's not necessarily indicative of a problem with Tab Stash. You can paste the log here if you want help interpreting it, or if you want to dig deeper yourself, the easiest way to sort out which messages are relevant is to look for messages from "index.js", "stash-list.js" or "options.js".


Hope this helps!

**Comment by selster** [comment] 2020-02-16 08:16
If you show me how you make the Show Stashed Tabs in a Tab then I'll try to, gosh I bet you already know how to do this




Get Outlook for Android







On Sun, Feb 16, 2020 at 12:15 AM -0800, <selster@san.rr.com> wrote:










I eventually figured away around it but it meant uploading several hundred PDFs to Dropbox and then asking my colleague to to download from there, it would have been much more efficient if I could have just waited for your program to generate a The page with all my tabs and their stashes, and then sent him the URL






On Sun, Feb 16, 2020 at 12:09 AM -0800, "Josh Berry" <notifications@github.com> wrote:












Ahh okay, I misunderstood. A couple quick things to (double-)check:

Right-click on the Tab Stash icon in your toolbar, and choose "Show Stashed Tabs in a Tab". Does this open the Tab Stash page for you as you would expect?
Right-click on the Tab Stash icon in your toolbar, and choose "Manage Extension". This will open the add-on settings for Tab Stash. Then click on "Options", and check if "Automatically show your stashed tabs in a new tab" is selected. If you select it, does this bring back the behavior you were looking for?



If neither 1 or 2 work for you, here's how you can collect debugging info:

Open a new tab and go to about:debugging.
Choose "This Firefox" in the sidebar
Find Tab Stash in the list of add-ons and click "Inspect". This should open the Firefox developer tools.
Click on the "Console" tab in the developer tools to see log messages and such.
Try to reproduce the problem you were seeing before.



NOTE: Logs for some internal browser things show up here as well, so even if you see errors, it's not necessarily indicative of a problem with Tab Stash. You can paste the log here if you want help interpreting it, or if you want to dig deeper yourself, the easiest way to sort out which messages are relevant is to look for messages from "index.js", "stash-list.js" or "options.js".


Hope this helps!

**Comment by josh-berry** [comment] 2020-02-16 18:28
Hi Steve, sadly the "Show Stashed Tabs in a Tab" URL is specific to your browser. There is an open feature request, #11, which I hope to get to soon that might do something similar to what you want—import/export stashes in a human-readable way.

I've shied away from generating a URL for stashes because of the privacy concerns—sharing a stash through a URL would mean that stash would have to be accessible to the Internet somehow, and since this is a spare-time project for me, I'm not sure I can commit the time/resources necessary to make sure it is properly secured and doesn't share your data in ways you might not expect.

All that said, there's one helpful trick for sharing lots of links that works with the Firefox bookmarks manager:

1. Open the bookmarks manager: Firefox Menu > Library > Bookmarks > Show All Bookmarks.
2. Find the Tab Stash folder you want to copy and click it in the sidebar.  You can also Shift+Click to select multiple folders.
3. Press "Ctrl+C" (on Windows) or "Cmd+C" (on Mac).
4. Paste the bookmarks into an email message, text message, etc.
5. If you're pasting into an app that supports HTML, you should get a nicely-formatted list of clickable links with the items from your stash. If you're pasting into an app that only supports text, you will get a list of URLs for each of the items in your stash.

This isn't as nice as having a Tab Stash UI, but hopefully this workaround helps you share links with your colleagues without going through a difficult manual process.

**Comment by selster** [comment] 2020-02-16 20:06
Thanks so much.!!!




Get Outlook for Android







On Sun, Feb 16, 2020 at 10:28 AM -0800, "Josh Berry" <notifications@github.com> wrote:












Hi Steve, sadly the "Show Stashed Tabs in a Tab" URL is specific to your browser. There is an open feature request, #11, which I hope to get to soon that might do something similar to what you want—import/export stashes in a human-readable way.



I've shied away from generating a URL for stashes because of the privacy concerns—sharing a stash through a URL would mean that stash would have to be accessible to the Internet somehow, and since this is a spare-time project for me, I'm not sure I can commit the time/resources necessary to make sure it is properly secured and doesn't share your data in ways you might not expect.



All that said, there's one helpful trick for sharing lots of links that works with the Firefox bookmarks manager:



Open the bookmarks manager: Firefox Menu > Library > Bookmarks > Show All Bookmarks.

Find the Tab Stash folder you want to copy and click it in the sidebar.  You can also Shift+Click to select multiple folders.

Press "Ctrl+C" (on Windows) or "Cmd+C" (on Mac).

Paste the bookmarks into an email message, text message, etc.

If you're pasting into an app that supports HTML, you should get a nicely-formatted list of clickable links with the items from your stash. If you're pasting into an app that only supports text, you will get a list of URLs for each of the items in your stash.





This isn't as nice as having a Tab Stash UI, but hopefully this workaround helps you share links with your colleagues without going through a difficult manual process.

**Comment by selster** [comment] 2020-02-16 20:09
If I get  "Show Stashed Tabs in a Tab" working again, is it designed for me to be able to copy that page and paste it into an email program or a word and have all the links be live? That way I as a user am choosing to copy it and you wouldn't be putting it in a URL which brings up the privacy concerns? Are users allowed to buy your program or make a contribution?




Get Outlook for Android







On Sun, Feb 16, 2020 at 10:28 AM -0800, "Josh Berry" <notifications@github.com> wrote:












Hi Steve, sadly the "Show Stashed Tabs in a Tab" URL is specific to your browser. There is an open feature request, #11, which I hope to get to soon that might do something similar to what you want—import/export stashes in a human-readable way.



I've shied away from generating a URL for stashes because of the privacy concerns—sharing a stash through a URL would mean that stash would have to be accessible to the Internet somehow, and since this is a spare-time project for me, I'm not sure I can commit the time/resources necessary to make sure it is properly secured and doesn't share your data in ways you might not expect.



All that said, there's one helpful trick for sharing lots of links that works with the Firefox bookmarks manager:



Open the bookmarks manager: Firefox Menu > Library > Bookmarks > Show All Bookmarks.

Find the Tab Stash folder you want to copy and click it in the sidebar.  You can also Shift+Click to select multiple folders.

Press "Ctrl+C" (on Windows) or "Cmd+C" (on Mac).

Paste the bookmarks into an email message, text message, etc.

If you're pasting into an app that supports HTML, you should get a nicely-formatted list of clickable links with the items from your stash. If you're pasting into an app that only supports text, you will get a list of URLs for each of the items in your stash.





This isn't as nice as having a Tab Stash UI, but hopefully this workaround helps you share links with your colleagues without going through a difficult manual process.

**Comment by josh-berry** [comment] 2020-02-16 20:16
> If I get  "Show Stashed Tabs in a Tab" working again, is it designed for me to be able to copy that page and paste it into an email program or a word and have all the links be live? That way I as a user am choosing to copy it and you wouldn't be putting it in a URL which brings up the privacy concerns?

Not right now, but something like this is exactly what I want to add in the future--an easy way to copy multiple links or groups both into and out of Tab Stash.

Are you still having trouble with "Show Stashed Tabs in a Tab"?

> Are users allowed to buy your program or make a contribution?

Thank you for asking, but I don't have a way to accept donations right now—at least not monetary donations. :) If you have the time and interest, pull requests for bug fixes or new features are always welcome though!

**Comment by josh-berry** [comment] 2020-03-08 23:19
Hi Steve, I'm going to close this issue out since there are already a couple open feature requests for import/export or copy/paste functionality (#11 and #17), but please feel free to re-open if you're still having problems with showing the stash.

In the meantime, I added a wiki page with the instructions for copying bookmarks out of Tab Stash, for use as an easy reference: https://github.com/josh-berry/tab-stash/wiki/Copying-Bookmarks-Out-of-Firefox

Hope this helps!

**Closed by josh-berry** 2020-03-08 23:19 UTC
Labels: support request
