### ISSUE TITLE
Tab-group sidebar, accidentally clicking on the mouse-over icons when trying to expand/display the group, deleting the group instead.

### ISSUE THREAD

**Issue by mrwiggleslol** [josh-berry/tab-stash#393] opened 2023-09-03 14:56 UTC
### Problem Statement
When the Tab Stash is displayed as a narrow side-bar, if you hoover your mouse over the group you want to uncollapse, it'll display the mouse-over menu/icons. The one closest to the '<'-button is "DELETE THIS GROUP" and the second closest is "OPEN ALL TABS, THEN DELETE THIS GROUP". I don't want to have to pay attention to how I aim my mouse, I just wanna click it. I also dont wanna delete the groups even though you probably can recover them.

### Preferred Solution(s)
I'd prefer it if I could select which buttons from that menu I wanna display on mouseover. It'd probably also be good to change the location of the mousover popup slightly or something.

### Alternative Solution(s)
Move the icon 'bar/menu' more to the left. Or move it somewhere else.

THANKS GOOD SIR IF YOU READ THIS YOURE A HERO BUT EVEN IF YOU DONT YOU STILL ARE FOR CREATING FREE TECH. TNX

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2023-09-03 16:16
First and most importantly: Yes, it is possible to recover deleted tabs, so long as you're on the same computer you used to delete them. In the Tab Stash menu (next to the search bar), choose "Deleted Items...", and then use the blue "Stash" button to restore anything you deleted by mistake.

There are some UI changes coming in the next version of Tab Stash that will hopefully help with deleting things by mistake—the "Delete Group" option will be hidden inside a menu, and the collapse/uncollapse button will be moved to the left (away from the other buttons). Here's a preview of what it will look like in the sidebar:

<img width="324" alt="Screenshot 2023-09-03 at 09 09 02" src="https://github.com/josh-berry/tab-stash/assets/1203893/69fd6bca-3ced-4604-a360-e374e104cf53">

(You might even be able to spot a couple other new features in that screenshot... ;) )

Being able to choose which buttons to show is tracked in #310, so I'll mark this issue as a duplicate of that one, but I hope this helps! Let me know if you have any more questions.

> THANKS GOOD SIR IF YOU READ THIS YOURE A HERO BUT EVEN IF YOU DONT YOU STILL ARE FOR CREATING FREE TECH. TNX

And thanks, this is really nice to hear! I'm glad it's helpful!

**Closed by josh-berry** 2023-09-03 16:16 UTC
