### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Aestarii** [josh-berry/tab-stash#291] opened 2022-09-21 17:09 UTC
### Question
Does Tab Stash consume a lot of CPU? I've been testing extensions one by one for CPU usage, since my fan has been going nonstop with Firefox open lately, and enabling Tab Stash (which, alas, I do love) looks like the culprit. As soon as I re-enable it, the temp skyrockets 30-50 degrees and the fans start blaring. When I disable it, it goes back to normal. I've got to stop using Tab Stash for the moment because of that. If you're able to fix that, though, I'd love to re-enable. 

### System Details

- **OS Version:** Mac OS Mojave 10.14.6
- **Browser Version:** Firefox 105
- **Tab Stash Version:** 2.10.3

**Comment by josh-berry** [comment] 2022-09-21 18:10
hm, there is a known issue that can cause high CPU usage - #240. It will be fixed in the next release (working through some final build issues on that with Mozilla, but it should come out very soon).

Can you please try the workaround here and let me know if it helps:

https://github.com/josh-berry/tab-stash/issues/240#issuecomment-1116344578

If it doesn't help, then this may be a new issue, and I'll have some more questions for you:

1. Roughly (order of magnitude estimate is fine) how many bookmarks you have overall (including outside of Tab Stash)
2. How many groups and tabs you have saved in Tab Stash
3. Any particular situations in which you see the CPU usage increase? e.g. after performing certain operations in Tab Stash or Firefox

Hope this helps!

**Comment by josh-berry** [comment] 2022-10-02 01:23
Since I haven't heard back, I'm going to assume this is a duplicate of #240, which should already be fixed in the latest release. But if you do hit this issue again, feel free to let me know! (And if you can include the answers to the questions above, that will help with faster diagnosis.)

**Closed by josh-berry** 2022-10-02 01:23 UTC
