### ISSUE TITLE
Preserve favicon and title when site goes offline

### ISSUE THREAD

**Issue by gregpettit** [josh-berry/tab-stash#184] opened 2021-12-03 15:35 UTC
I use a VPN to access several web applications hosted on a private WAN. The VPN is not connected 24/7, and when the browser is no longer able to access those sites, 2 potential problems occur:

1. The favicon in the Stash turns into a generic "tab" icon
2. Sometimes the title of the page becomes "Problem loading page" per the Firefox default

The potential problems with simply preserving once fetched revolve around the remote site updating. What if they change their title? What if they change their favicon? Tab Stash of course would want the newest and best to be shown in the stash, right? It is trying to be helpful, not hurtful to the user.

However, I believe that people wanting to update their stashed tab need simply re-stash it. This will collect the information anew. You could even have a refresh button at the top of the stash group to do them all at once.

By the way, I have tried many "tab management" extensions over the years, and this one is by far the one that works best with my mental concept of how tabs should work. Love it. Thanks!

**Comment by josh-berry** [comment] 2021-12-04 19:18
hm... I also routinely use sites behind a VPN and I can't say I've noticed this problem. Is this happening with pages that are open as tabs in the browser or is it happening with stashed tabs?

For fetching missing icons, there is a "Fetch Missing Icons" option in the Tab Stash menu that will try to fill in all the icons from all the pages in your stash. (Be warned however: it can take a while to run, since it must load each and every page to find the icon.)

For icons that just get out of date, Tab Stash will track the icons from open tabs, and any time a new icon is found for a URL that's in the stash, Tab Stash will automatically update it. So you don't even need to un-stash and re-stash--just open the page to get the updated icon and Tab Stash will remember it.

Titles are a bit different though. Since the titles themselves are saved in your bookmarks, and it's also possible to *edit* those titles through Firefox's bookmark editor, Tab Stash will not update titles automatically. In that case, you're right that you can re-stash the tab, or you can manually edit the title in the bookmark editor and Tab Stash will pick it up.

Hopefully this helps to explain what's going on. Does this address your concern?

> By the way, I have tried many "tab management" extensions over the years, and this one is by far the one that works best with my mental concept of how tabs should work. Love it. Thanks!

Thanks, I'm really glad to hear it! 😄

**Comment by AussieGit** [comment] 2021-12-10 06:26
Firstly, best tab management tool yet and I have used far, far too many as I can have up to 100 tabs opened during research. Tab stash helps with memory issues, easy to add and open stashed tabs and by saving in bookmarks, I love that I can go in and add a title to the stashed tabs for my easy reference. Outstanding Add-on!! Thank you.

Issue I have now is similar to OP however it doesn't just happen with VPN usage. Everytime I shut down my browser Firefox, the favicons of all stashed tabs are blank. This only started happening in past 3 or 4 days. Using ver 2.10.1 and FF v95.0 which I only updated today but the missing favicons was also happening in FFv94.

As I have around 400 stashed tabs, fetching missing icons each time is not really a productive option & the favicons make it so much easier to find a particular tab(s) quickly.

**Comment by josh-berry** [comment] 2021-12-12 21:59
@AussieGit:

Have you changed any of your browser settings around remembering history, storing cookies, etc.? In particular, "Delete cookies and site data when Firefox is closed" may cause this behavior, and I think changing the history settings to "Never remember history" may have an impact as well.

If not, can you check if Tab Stash is reporting any errors in the background page's logs? Here's how: https://github.com/josh-berry/tab-stash/wiki/Collect-Error-Logs

It would be good to check after a fresh restart of the browser, and after adding something new to the stash.

> Firstly, best tab management tool yet and I have used far, far too many as I can have up to 100 tabs opened during research. Tab stash helps with memory issues, easy to add and open stashed tabs and by saving in bookmarks, I love that I can go in and add a title to the stashed tabs for my easy reference. Outstanding Add-on!! Thank you.

Thanks, I'm happy to hear it!

**Comment by josh-berry** [comment] 2021-12-18 18:20
@gregpettit Ahh got it. Tab Stash uses IndexedDB for storing the favicon cache so anything that clears browser-local storage would probably clear IndexedDB as well.

One thing you might try (if you’re comfortable with it) is to allow Tab Stash to run in private windows. I think Firefox uses a different storage policy for extensions with this option enabled. I don’t know if it will help, but it might be worth a try (and I’d be curious to hear what happens).

**Comment by AussieGit** [comment] 2021-12-20 05:15
@josh-berry  The error logs may as well be in Martian to me. Got a headache just looking at them :) I have attached screenshot of the logs and below the red line is the newest entries after reopening. 

I know everyone says Ï haven't changed anything or added anything"and to the best of my knowledge, I haven't except for the minor update to FF. My browser is not setup to delete cookies and always remembers history.

It's only a very minor issue and the way I solve it is by opening eith bookmarks or history from the Tab-stash dropdown box then clicking tab-stash and all the icons are back. 

Thanks for a brilliant extension but more so for the superb & prompt support. It shows you really care about your work and continued development. Very much appreciated.

<img width="1710" alt="Tabstash2" src="https://user-images.githubusercontent.com/26198909/146715057-1058eade-f187-4f72-8d9d-c8edd71c847f.PNG">

**Comment by josh-berry** [comment] 2021-12-27 17:21
@AussieGit Well, your headache paid off, because based on your logs, and also your comment that:

> the way I solve it is by opening eith bookmarks or history from the Tab-stash dropdown box then clicking tab-stash and all the icons are back.

...it sounds like this might be the same issue as #181, just with different symptoms. When your favicons go missing, it would be interesting to see if you can delete stashed tabs or if nothing happens like in #181? I'd wager you won't be able to delete any tabs if your favicons are missing.

Either way, though, I think the fix would also be the same as #181.

(If you're curious: The reason the same bug can cause problems with deleted items and with favicons is that both of these things use the same communication mechanism between the Tab Stash UI and the Tab Stash background process, and it's this communication mechanism that's failing.)

**Comment by josh-berry** [comment] 2022-01-11 06:04
Hi folks, I'm going to go ahead and close this as a duplicate of #181, since the fix for @AussieGit's favicon issue should be the same as the fix for that bug, and @gregpettit it sounds like cache-clearing might be causing the problem for you.

But if you're seeing any new/weird behavior other than what's already been discussed, feel free to leave another comment here or open a new issue. Thanks!

**Closed by josh-berry** 2022-01-11 06:04 UTC
