### ISSUE TITLE
Adding Keyboard Shortcuts for Tab Stash Homepage

### ISSUE THREAD

**Issue by Zhu-Justin** [josh-berry/tab-stash#159] opened 2021-09-21 20:40 UTC
### Problem Statement

I search around my tabs a lot, so a keyboard shortcut to search my tabs on the tab stash homepage would be nice. I also expand and collapse the tab stash homepage a lot to move around my tab stash folders a lot, and a keyboard shortcut for that would be nice as well.

### Preferred Solution(s)

The ideal solution is keyboard shortcuts for searching and collapsing/expanding all tab stash folders in the home folder.

### Additional Context
<img width="527" alt="image" src="https://user-images.githubusercontent.com/31556466/134259640-dd06cab1-fc10-49da-b887-8e65af20f947.png">

I would like to find a way to type a key (i.e. "/") and the tab stash homepage can focus on the search bar, enabling me to search. Similarly, a key (i.e. "f") toggles between expand all tabs and collapsing all tabs. Having a way to navigate through this website using no mouse (i.e. vim keybindings) would make this a home run!

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2021-09-29 16:34
Hi, this seems like a duplicate of #131, so to keep all the discussion in the same place, I'm going to close this one—but please take a look at that one and see if there's anything you'd like to add. Thanks!

**Closed by josh-berry** 2021-09-29 16:34 UTC
