### ISSUE TITLE
Opening Dev Tools causes a crash when activating an unknown tab

### ISSUE THREAD

**Issue by KarboniteKream** [josh-berry/tab-stash#338] opened 2023-02-22 05:44 UTC
### Crash Details

```text
Browser: Mozilla Firefox 110.0 20230214051806 (mac aarch64)
Extension: Tab Stash 2.12.0.1 (development, commit 244f86a3e298a238f0177b55ca7710661f191d26)

Got activated event for unknown tab 814
expect@moz-extension://eea4455b-9fb5-4da9-8fce-181ec9f5fdfe/assets/button.js:8112:9
whenTabActivated@moz-extension://eea4455b-9fb5-4da9-8fce-181ec9f5fdfe/assets/menu.js:1589:23
handler@moz-extension://eea4455b-9fb5-4da9-8fce-181ec9f5fdfe/assets/menu.js:46:16
```

### Installed Extensions
- Privacy Badger
- TWP - Translate Web Pages
- uBlock Origin

Also reproducible without other extensions.

### Describe the Crash

1. Opened a new private window, and opened the Tab Stash sidebar and tab
2. In the Tab Stash tab, I opened the Dev Tools and added `?trace=model,tabs` to the URL
3. Opened a new tab, and clicked on a bookmark to open GitHub
4. Opened a new tab, and clicked on a bookmark to open WaniKani
5. In the WaniKani tab, I pressed Cmd+Option+I to open the Dev Tools
6. Closed the WaniKani tab with Cmd+W, which causes the crash to appear in Tab Stash sidebar

This is reproducible 100% of the time, even with a single tab.

### Additional Details

Trace logs, without any information removed:
https://gist.github.com/KarboniteKream/bfbb5251c84c26a81f6fca1748b27f92

**Comment by josh-berry** [comment] 2023-02-25 06:33
Thanks for the detailed steps and the trace info; I'm able to reproduce it on my side as well. The deciding factor seems to be whether a tab is closed while it has the focus and while devtools are open for that tab. It doesn't actually seem to matter which tab it is, whether it's in private-browsing mode, etc.

Looking at what the browser reports, I don't see any tab returned with that ID, so I'm assuming it's the ID of the devtools tab. I'm mystified as to why Tab Stash is getting an "activated" event for a devtools tab/window that's being _closed_, but I'm thinking I'll just start ignoring events for windows that the browser hasn't told Tab Stash about before (rather than assuming something is wrong), and that should avoid these types of bugs in the future.

**Comment by josh-berry** [comment] 2023-02-25 06:40
Should be fixed in the next release, thanks again for reporting it!

**Closed by josh-berry** 2023-02-25 06:40 UTC
Labels: i-bug
