### ISSUE TITLE
Please add a more convinient way to sort tabs between groups and stashing tabs to a predifined group 🙏

### ISSUE THREAD

**Issue by qchristianp** [josh-berry/tab-stash#143] opened 2021-07-11 21:40 UTC

**Comment by josh-berry** [comment] 2021-07-11 23:21
Duplicate of #57 (for sorting) and #110 (for saving to a predefined group)—please check the discussion on those two issues, and if your idea isn't covered by one of those, feel free to [open a new feature request](https://github.com/josh-berry/tab-stash/issues/new?assignees=&labels=&template=feature_request.md) (but please answer all the questions in the form). Thanks!

**Closed by josh-berry** 2021-07-11 23:21 UTC
