### ISSUE TITLE
Memory usage issue, probably loading all bookmarks at once

### ISSUE THREAD

**Issue by lumpsoid** [josh-berry/tab-stash#512] opened 2024-08-07 21:43 UTC
### System Details

- **OS Version:** Arch Linux 6.10.3-arch1-1
- **Browser Version:** 128.0.3-2 (64-bit)
- **Tab Stash Version:** 3.0.1

**Installed Browser Extensions:**

- disabled for the test

### Describe the Bug

high consumption of the ram with large amount of bookmarks

### Steps to Reproduce

1. when enabling Tab Stash
2. and open Tab Stash in sidebar or new tab
3. it loaded all bookmarks at once even if I will never scroll until end

### Expected Behavior

1. probably, load all bookmarks in the state and render only portion of UI and lazy load on scroll the rest
2. with this search still will be able to work, and the page would not take large amount of RAM

### Impact

I'm having 1553 bookmarks right now with Tab Stash and it is eating 150 MB of RAM

### Additional Details

- in address field `about:memory`
- click button `Measure`
- filter by extension `Internal UUID`
- navigate to the `extension` part
```
169.18 MB (100.0%) -- explicit
├──168.45 MB (99.57%) -- window-objects
│  ├──152.75 MB (90.29%) ++ top(moz-extension://c553bab0-83c8-4c0d-8088-cc56624d17ec/stash-list.html?view=sidebar, id=1148)
│  ├───12.92 MB (07.64%) ++ top(moz-extension://c553bab0-83c8-4c0d-8088-cc56624d17ec/_generated_background_page.html, id=1146)
│  └────2.78 MB (01.64%) ++ top(moz-extension://c553bab0-83c8-4c0d-8088-cc56624d17ec/options.html, id=1217)
└────0.73 MB (00.43%) ++ images/content/vector
```

stash-list.html taking 152.75 MB (90.29%) of RAM, 

for the record
if you will see that in the result there would be `... ghost ...` or `... detached ...` it means that it don't hold memory anymore and either in the process of freeing it or it's waiting for other processes to take over it

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2024-08-07 22:19
Yep, this is a known improvement I want to work on. It's tracked in #97 (though of course I understand it's not obvious these two are connected). So I'll go ahead and mark this as a duplicate of that one. Thanks for reaching out!

**Closed by josh-berry** 2024-08-07 22:19 UTC
