### ISSUE TITLE
Loss of all the stashed tabs

### ISSUE THREAD

**Issue by Sahrio** [josh-berry/tab-stash#49] opened 2020-03-05 08:36 UTC
### Describe the Bug
Losing all the stashed tabs with no apparent way of restoring them back.

### Steps to Reproduce
*Detailed steps to reproduce the problem:*
1. Open your browser and some tabs in it
2. Open another instance of your browser and leave it in blank.
3.Close the first instance with tabs.
4. Navigate with the second instance, create a stash and close the browser

### Expected Behavior
You should have lost all your previous stashes and whenever you open the Tab Stash window you would be welcome by a blank page.

### Screenshots
Solved it before taking this 0_0 (Sorry)
### Desktop (please complete the following information):
 - **OS: Windows 10**
 - **Firefox Browser Version:** *[73.0.1 (64-bit)]*

### Additional Context

The program seems to create a new parent folder.
Maybe the firefox version used when the bug happened was a previous one.

**Comment by josh-berry** [comment] 2020-03-06 17:50
Hi, sorry for the inconvenience. I'm glad you were able to solve it yourself, and I definitely appreciate you filing the bug anyway. :)

It sounds similar to issue #41 but I'm guessing with a different cause. My best guess is that Tab Stash in each of your browsers created two different root folders, and then Firefox Sync decided to keep both of them, and Tab Stash wasn't sure which one to use.

The next release of Tab Stash should detect this condition and give you a notification with a link to instructions on how to resolve it. If you're interested, you can preview the instructions here: https://github.com/josh-berry/tab-stash/wiki/Problems-Locating-the-Tab-Stash-Bookmark-Folder

(Note that when it says "newer versions of Tab Stash", it's referring to a release that hasn't happened yet; Tab Stash 2.6 will contain the changes.)

I'll keep this open in the meantime until 2.6 is released. If you have any feedback/additional info to share until then, let me know. Thanks again!

**Comment by josh-berry** [comment] 2020-04-26 22:41
Just to keep my list of to-dos straight, I'm going to go ahead and close this out as a duplicate of #41. As I mentioned, the fix will be in the next Tab Stash release.

**Closed by josh-berry** 2020-04-26 22:41 UTC
Labels: bug
