### ISSUE TITLE
Stashed Tabs - Selecting Multiples; Browser re-opening; Where to Open

### ISSUE THREAD

**Issue by Brandon8D** [josh-berry/tab-stash#56] opened 2020-05-02 18:54 UTC
I chose your program because of the simple UI. I got it because I have too many tabs open (had over 1000). I am interested in a wide range of subjects, and so far have created 19 groups to contain my Tabs. But the program has some major shortcomings that are a real problem, so I cannot recommend it yet.
Along with my Bug fix request,  these ENHANCEMENTS will  allow for fast sorting / grouping and use, and make it a 5* program:

1.   Really needed: Able to select multiple tabs in one group so to move them to another group (or to delete I suppose). This will speed up one's grouping setup a lot. This allows one quickly to fix stashing to a wrong group selected by mistake.

2.   If a tab is already open, the browser just needs to go to that already opened tab, not open another.
    Sometimes it does, sometimes it doesn't.

3.   It needs to open tabs next to the current viewed tab, not at end of all tabs. (or allow the choice).
    Example: I have a group I call "Office". I want it at the left end of my Tabs. But it opens on the right end. Maybe I want to open 1 tab or 4 or a small Group next to something I am working on.

Thank you.

(I could not find how to add a label e.g. "Bug".)

**Comment by josh-berry** [comment] 2020-05-02 22:04
I'm going to go ahead and close this one as a duplicate of your earlier #55 since I think I covered each of these points there.

No worries on the labels—only project contributors (currently just me) can add them, and I use them as a way to tell which issues I've looked at/responded to and which I haven't yet.

**Closed by josh-berry** 2020-05-02 22:04 UTC
