### ISSUE TITLE
Contribute to translation

### ISSUE THREAD

**Issue by dieudo4** [josh-berry/tab-stash#297] opened 2022-10-23 22:37 UTC
### Problem Statement

I would like to contribute to translate this extension. Is it possible ?

### Preferred Solution(s)

Is it already possible?

### Alternative Solution(s)

If it is, would you make it more visible?
If it's not, would you make it so?

### Additional Context

I really appreciate this extension : )

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2022-10-29 19:53
Glad to hear Tab Stash is useful for you, and thanks for asking! It's not possible right now unfortunately. I'll have to do quite a bit of work to allow for translations to other languages. But I do want to allow for translations at some point.

Keep an eye on issue #130 for the latest; I'll mark this as a duplicate of that one just to keep things organized. And again, I really do appreciate the offer to help!

**Closed by josh-berry** 2022-10-29 19:53 UTC
