### ISSUE TITLE
Tab-stash extension options page in Firefox disappears after a few seconds

### ISSUE THREAD

**Issue by TechTony2016** [josh-berry/tab-stash#565] opened 2024-12-23 14:43 UTC
### OS Version

Windows 11 Pro

### Browser Version

Firefox 133.0.3

### Tab Stash Version

3.1.1

### Non-Standard Browser Settings

n/a

### Installed Extensions

All disabled, but options page still disappears.

### Problem Description

Tab-stash extension options page in Firefox disappears after a few seconds

### Steps to Reproduce

Try to manage tab-stash from Firefox and the options menu disappears after a few seconds.

### Expected Behavior

Options page should not disappear.

### Impact

Makes learning and using tab-stash difficult, if not "not worth the time".

### Additional Details

As the options page loads, the scrollbar thumb increasingly gets smaller until finally the options page disappears. Weird.

### Vote for This Issue

- [X] _Readers: If you are also experiencing this problem, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button below.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system._

**Comment by josh-berry** [comment] 2024-12-23 16:02
Can you send me a screen recording of this happening? I have a win11 box with Firefox 133 and I'm not able to reproduce this at all. Thanks!

**Comment by TechTony2016** [comment] 2024-12-23 19:57
I installed anew, Firefox 128.xesr and now the tab-stash options page behaves correctly.

**Comment by josh-berry** [comment] 2024-12-23 20:17
Glad to hear it! I'll close this out but let me know if you run into it again!

**Closed by josh-berry** 2024-12-23 20:17 UTC
Labels: i-bug
