### ISSUE TITLE
Issue when draging and dropping from one stash to another

### ISSUE THREAD

**Issue by rayman89** [josh-berry/tab-stash#272] opened 2022-07-06 16:46 UTC
When using tab stash on a new tab view and dragging from one stash to another the first attempt will show like dragging a picture of the whole list, the second one will work as intended. I'm using Firefox 102 regular version. The tab stash is over 500 tabs.
As a work around if you drag from the favicon rather than the title it works as intended all the time.

![image](https://user-images.githubusercontent.com/5449042/177601889-69ea6431-77c5-4ef4-a7a4-00d6cbc2a8f2.png)

**Comment by josh-berry** [comment] 2022-07-09 18:34
In the screenshot you've pasted, it looks like a drag operation was triggered for the entire group of tabs.

If you press and hold the mouse button on the tab title and wait a moment before you start to move the mouse, do you still have this issue or does only the tab get dragged as you intended? This might have something to do with how drag and drop is detected and how the browser decides whether you are dragging a single tab or the whole group.

In future, please make sure to fill out the whole bug-reporting form, because you've not included some important information:
* What other extensions do you have installed?
* What OS are you running?

**Comment by josh-berry** [comment] 2022-07-16 20:22
Got it. I have a rough theory as to what might be happening, though I'm not able to reproduce this on my machine so far. I'll keep experimenting though and see what I can figure out.

**Comment by SafetyCar** [comment] 2022-07-17 01:06
I am also having some problems here and there with drag and drop being too easy to grab the group instead of the individual item.
Tends to fail once or twice in a row and then start working again.
I'm trying to find something reproducible but no luck. Not sure if hearing some of your theory could help a bit with that.

**Comment by josh-berry** [comment] 2022-07-17 21:22
Well my original theory was that somehow events (mouse press + drag start) were being delivered in the wrong order, but if pressing+holding while moving the mouse doesn't improve things, then it's probably not that.

My next theory is that the browser is sometimes picking the wrong element from which to start the drag operation. The mouse-press event (which enables drag/drop) gets delivered to both the tab AND the group (since both should be draggable). But then, when you start moving your mouse, the browser is occasionally picking the group, rather than the tab, for the drag-start event.

As to *why* the browser would sometimes pick the group instead of the tab to start the drag operation... I have no idea. That's not how events are supposed to work—the browser shouldn't randomly pick an element to get the event, it's always supposed to start with the inner-most thing and work its way out until every element in the path has received the event or some element in the middle says "stop, I've got it, you don't need to let my parent know about this".

Anyway, if I can reproduce it locally, then I can check if my theory is correct. (If it is, then this should be an easy fix—stop the mouse-press event from bubbling up to the parent, so drag+drop is never enabled on the group.)

**Comment by josh-berry** [comment] 2022-07-29 03:12
OK, so I *think* I have a fix for this which will go into the next release. But I've only been able to reproduce it a single time on my system, so I can't say for sure.

If I'm right, then once the next release comes out and you upgrade, this should go away. But if I'm *not* right, please let me know and I'll reopen this. :)

**Closed by josh-berry** 2022-07-29 03:12 UTC
Labels: i-support request
