### ISSUE TITLE
Add sidebar in Tab Stash Chrome version

### ISSUE THREAD

**Issue by sdzkHelince** [josh-berry/tab-stash#416] opened 2023-10-29 12:03 UTC
### Problem Statement

In the Firefox version of extension, there's an ability to open it in a sidebar. However, in Chrome version, you can only open it in a pop-up, even tho Chrome now supports opening extensions in a sidebar.

### Preferred Solution(s)

Add an ability to open Tab Stash in a sidebar.

### Additional Context

I know that you said, that you'll not work on Chrome version as hard as on Firefox one, because you don't use any Chrome-based browser, but tbh, opening in sidebar is the only important feature Chrome version is missing, and AFAIK it's not that hard to implement it.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2023-10-29 20:16
Yeah, I unfortunately don't expect to have any time for Chrome in the foreseeable future (as mentioned in #52). It's nice to know that Chrome has a sidebar now, but this should probably be tracked as part of #52 itself, so I will mark this as a duplicate of that one.

**Closed by josh-berry** 2023-10-29 20:16 UTC
