### ISSUE TITLE
Feature Request: Button to Move Stashed Tab to the Top of Folders Stack!

### ISSUE THREAD

**Issue by Zhu-Justin** [josh-berry/tab-stash#257] opened 2022-05-15 18:36 UTC
Thank you Josh for an amazing extension! I cannot emphasize enough how much I love this extension.

I love being able to quickly create folders that group a new unstashed tab, but I lately have been noticing that by creating a lot of stashed tab folders, it can be difficult to sort the tab folders in order of priority.

I was wondering if you could add a button that moves a stashed tab folder all the way to the top in the sidebar so that these higher-priority tab stashes stay at the top of the tab stash sidebar -- effectively we can make tab stash a "tab stash stack"!

For example, I have this stashed folder called __TODO that has been pushed to the bottom of the tab stash list because I also created some new stash groups like "React" and "Javascript". It would be great if -- rather than dragging __TODO all the way up with a long mouse click -- we could simply click on a button next to the `"stash all", "stash active tab", "open all tabs in group", "open all tabs in group and delete", "delete the group"` icons called `"move tab group to top"`.

<img width="156" alt="image" src="https://user-images.githubusercontent.com/31556466/168488618-e9aa605b-5995-4d66-b661-8a7856a259cb.png">

<img width="176" alt="image" src="https://user-images.githubusercontent.com/31556466/168488771-8e8c735b-f8e0-49e3-b4b4-183ff732e524.png">

<img width="215" alt="image" src="https://user-images.githubusercontent.com/31556466/168488895-36a1773e-e507-4cb6-8dcd-3eb7b2cb4318.png">

I hope this feature request is not too much trouble for you, and please let me know what I can do to help add this feature to the next version of tab stash! Thank you so much!

**Comment by josh-berry** [comment] 2022-05-21 18:29
Hi Justin, thanks, I'm glad to hear you're enjoying Tab Stash!

This sounds a lot like the feature request in #124, with the possible exception that in #124, when you "pin" a stash, it would always stay at the top. Would something like that work for you?

I see you've got JS and React in your stash list—I'm always happy to take PRs! Tab Stash uses Vue, which is similar to React in a lot of ways from what I understand. No pressure, of course, but if this is something you have time/interest in working on yourself, I'd be happy to work with you on it! Here's a quick primer on how/where to start: https://josh-berry.github.io/tab-stash/contributing.html

**Comment by josh-berry** [comment] 2022-06-11 18:32
I'm going to go ahead and mark this as a duplicate of #124, but if you disagree, do let me know!

**Closed by josh-berry** 2022-06-11 18:32 UTC
