### ISSUE TITLE
Dragging consecutive tabs to different stash fails

### ISSUE THREAD

**Issue by Erhannis** [josh-berry/tab-stash#295] opened 2022-09-30 23:36 UTC
### System Details
- **OS Version:** Ubuntu 20.04.5 LTS
- **Browser Version:** 105.0 (64-bit)
- **Tab Stash Version:** 2.11.0.1

**Installed Browser Extensions:**
None of my extensions are on the conflict list.
-
-

### Describe the Bug
I have tabs 1, 2, 3... in stash A.  I drag tab 1 from stash A to stash B, successfully.  I drag tab 1 from stash A to stash B, and nothing happens - no drag hints show up, nothing is done when I release the mouse button.  If, instead, I drag 1 to B and then 3 to B, it succeeds.  I _suspect_ the UI is silently selecting the next tab once one is dragged away, or something similar, and getting into a weird state, like certain handlers aren't registered or something.

### Expected Behavior
Dragging one tab to another stash, then the following tab to another stash, should succeed.

### Impact
I can just drag tabs in a different order - like, from the bottom up - but it's kindof a pain.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by safetycar** [comment] 2022-10-01 03:50
Could reproduce it.
Example: In a group with 5 elements, moving the 4th item and then trying to move the new 4th (prev 5th) seems to make the drag drop unresponsive.

**Comment by josh-berry** [comment] 2022-10-01 06:18
Strange, I myself just noticed this same issue today (before I had seen this bug). So yes, I will definitely look into this for the next bugfix release!

**Comment by josh-berry** [comment] 2022-10-02 01:22
Turns out there were some oddities in how the list of drag-and-droppable items were being tracked that was leading to this behavior. This is now fixed, and the fix will be in the next release!

(As a bonus, I wound up fixing another issue where dragged items would sometimes would sometimes get "stuck" in the wrong position. Who knew drag-and-drop could be so complicated...)

**Closed by josh-berry** 2022-10-02 01:22 UTC
Labels: i-bug
