### ISSUE TITLE
[NOT like #44] Show Stashed Tabs not working after a while

### ISSUE THREAD

**Issue by TheRealBax** [josh-berry/tab-stash#88] opened 2020-07-31 13:08 UTC
### System Details

- OS Version: Win 10
- Browser Version: FF 78.0.2
- Tab Stash Version: 2.6

### Describe the Bug

- Description: Show Stashed Tabs & Stash All etc. does not work after a while.

- Possible Solution: Unfortunately the solution, as described in #44, does not work for me. My problem might look the same, but could have another reason: after most likely overusing the tabs my Firefox runs into memory problems after a while. 

- Side effects: The standard FF bookmark-Star turns blue on every tab I visit as if I would have bookmarked the site, but i did not. It also stops working so do other "session" apps. The only one still working (in this field of operations) is the OneTab extension.

### Expected Behavior
The opposite of the above mentioned.

### Steps to Reproduce
Go crazy with tabs and hibernate the computer as often as possible.

### Impact
I'm frustrated.

### Additional Details
Quite hot and Corona plus my issue is #88 (the double of #44, still it seems to be the only relation), in short it's a mess.

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2020-08-01 02:00
So the first thing I would suggest is try to reduce your memory usage. If your computer is so low on memory that Firefox is unable to get memory from the OS, all manner of things in Firefox could go wrong (not just Tab Stash). 

If closing tabs, reducing memory usage, etc. hasn't helped, it's quite possible your bookmark/history data is corrupt in some way and not just the session data that would be cleared by #44. You mentioned:

> The standard FF bookmark-Star turns blue on every tab I visit as if I would have bookmarked the site, but i did not.

This to me seems quite telling—if this is true even for sites not saved in Tab Stash or other extensions which use bookmarks, it might be that the problem isn't your session data but your bookmark data itself, especially if the steps in #44 didn't help. Here are a couple more things you can try, in order from least to most disruptive:

1. Refresh Firefox: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings
2. Manually re-create your Firefox profile: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
   * Your Firefox profile contains all your settings, bookmarks, history, etc.
   * You will want to save your existing data using Firefox Sync, and sign in to Firefox Sync from the new profile to restore it just like you are setting up a new computer. (I would not suggest manually copying data over from the old profile, because if any of those files are corrupt in some way, you will wind up with the same problem all over again.)

**Comment by TheRealBax** [comment] 2020-08-14 09:01
Thanks a lot! The "bookmark star" problem only appears after some time, when FF reaches around 2GB memory. Even after closing tabs and freeing memory by suspending tabs it just continues using more and more memory. Typical FF bug I would say. Nr. 1 "refresh" did not work, I will try Nr. 2 later.

**Comment by josh-berry** [comment] 2020-11-06 19:39
Hi, sorry for the long delay on this, but I wanted to check back to see if you were able to solve the problem?

**Comment by josh-berry** [comment] 2021-04-03 05:52
I'm going to close this one out since I haven't heard back from you in a while. If you're still having this issue, please feel free to re-open/leave another comment here. Thanks!

**Closed by josh-berry** 2021-04-03 05:52 UTC
Labels: i-support request
