### ISSUE TITLE
Double clicking on unstashed tab does not switch tabs to selected tab

### ISSUE THREAD

**Issue by timoc** [josh-berry/tab-stash#12] opened 2019-05-22 16:43 UTC
**Describe the bug**
When i double click on a tab that is unstashed, it does not change the browser focus to that tab.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. open two tabs
2. Click on the one that is not open
3. See error

**Expected behavior**
When i double click on an unstashed tab, i expect the tab to be focussed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
being able to see the tab before you stash it saves hassle. the same feature would also be usefull for people who just want to cherry pick from a saved stash, not pop the item from the stash.

**Comment by josh-berry** [comment] 2019-05-22 21:29
Hi Tim, you should just be able to click once (don't double-click) and have it switch to the tab.

That said, I tried double-clicking just now and double-clicking on my system does switch to the tab, so I'm not able to reproduce this problem. Can you please provide your Firefox version and operating system so I can investigate further?

**Comment by timoc** [comment] 2019-05-23 07:21
I am now not able to reproduce it, but now i think of it, the scenario was where there were doubles of the tabs in the unstashed list that may have been in another window. A situation i cleaned up, but may still be applicable.

**Comment by josh-berry** [comment] 2019-05-23 16:54
Alright, thanks, that's a helpful pointer. I'll keep this open for now to investigate further.

**Comment by josh-berry** [comment] 2019-06-30 20:01
So I did some experimentation this afternoon and wasn't able to reproduce this myself, either, even with duplicate tabs in the same and different windows. (I found an unrelated issue where Tab Stash would switch to the wrong duplicate in the same window, but it would always switch to *something*.)

That said, I did run into something with similar symptoms myself recently (which didn't involve duplicate tabs) where Tab Stash couldn't switch to *any* tab because Firefox was just returning errors to all the WebExtension tab APIs. Restarting the browser fixed it, so I think something in my Firefox's internal state may have been messed up unrelated to Tab Stash.

In any case, given that neither of us have been able to reproduce it, I'm going to go ahead and close this issue, but if it happens again, please feel free to reopen it or file a new one.

**Closed by josh-berry** 2019-06-30 20:01 UTC
Labels: support request
