### ISSUE TITLE
(optionally) also bookmark unstashed tabs

### ISSUE THREAD

**Issue by AeliusSaionji** [josh-berry/tab-stash#395] opened 2023-09-07 23:44 UTC
### Problem Statement

Tab stash, when used as a vertical tab extension, promotes a "file manager"-esque approach to the browser. That is, I can open any number of firefox windows, scroll through the same "folders" and open the same "files" in each window. Stashed "tabs" no longer belong to any one window, as they do in a conventional internet browser.

However, this leads to a kind of trap;

Let's say I have 5 unstashed and unrelated tabs. I ignore them for a moment and begin working within some stashed tabs. I open a second window and open more stashed tabs, so I can reference two stashed tabs side by side.

I'm finished working on this subject. I no longer need the second window.

⚠️ **If I close the wrong window, I will lose my unstashed tabs** ⚠️ 

It's an unintuitive scenario. It's like I have two terminals open, but files created in one are inaccessible to the other, and can be lost when closing that terminal.

### Preferred Solution(s)

Bookmarking the unstashed tabs in some special stash would decouple them from being window dependent, and would also have the added benefit of sync pushing the unstashed across different PCs.

### Alternative Solution(s)

Alternatively, tab stash could keep track of unstashed tabs by some other mechanism of the developer's choosing. Perhaps tab stash could always sync unstashed tabs across all open windows.

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2023-09-09 03:58
Hi, thanks for the feature request. This is probably mostly a duplicate of #224, but let me touch on this part quickly:

> Let's say I have 5 unstashed and unrelated tabs. I ignore them for a moment and begin working within some stashed tabs. I open a second window and open more stashed tabs, so I can reference two stashed tabs side by side.
> 
> I'm finished working on this subject. I no longer need the second window.
> 
> **⚠️ If I close the wrong window, I will lose my unstashed tabs ⚠️**

This is actually by design. A key difference between Tab Stash and other tab management extensions is the idea that saving into the stash is an intentional action that must be triggered by the user.

I've frequently found that things which "auto-save" tabs often create more chaos and confusion than they solve, because it will save things you don't need, and *lose things you do need* (e.g. if you navigate away from the page you want to save by mistake).

Firefox offers some excellent built-in features for recovering tabs and windows which were closed by mistake. They're a bit hard to find (since they're buried under the "History" menu), but they work better than anything that could be built by an extension, since they also save some page state, navigation history, etc. in ways that extensions can't.

I'm sure this isn't a very satisfying answer, but I hope it helps to at least explain my thinking. Thanks again for sharing your thoughts, and feel free to add any additional comments you may have on #224!

**Closed by josh-berry** 2023-09-09 03:58 UTC
