### ISSUE TITLE
Hide all tabs from a group

### ISSUE THREAD

**Issue by qukhan** [josh-berry/tab-stash#106] opened 2021-01-25 14:08 UTC
### Problem Statement
I'd like to be able to hide all open tabs that belong to a group. I tend to stash tabs by topic and try to keep my tab count low. 

### Preferred Solution(s)
It be great if you could add a button to the group actions that would hide all open tabs that belong to that group.

### Alternative Solution(s)
Not too sure what to put in here.

### Additional Context
I guess a *show all* option could also be asked but I'm not sure what it would bring over picking the tabs in the Tab Stash panel.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2021-01-31 21:13
Hi, thanks for the feature request! I'll keep this in mind for a future release. I don't want to promise that I can add another button for this, because I think adding too many can quickly make the UI overwhelming and hard to understand. But I'll think on how something like "close/hide this group" can be accommodated.

In case you're not already aware, Tab Stash 2.7 added a "Close all stashed tabs" button to the "Unstashed Tabs" section. This isn't quite what you're asking for, since it closes/hides stashed tabs across *all* groups, but depending on your situation, you might still find it helpful. I use it quite frequently to sweep away all the tabs that are already organized, so I can just focus on the ones that don't have a home yet.

**Comment by josh-berry** [comment] 2022-03-18 05:04
In the next release, the "delete" button for the group will do double duty—you'll be able to middle-click it to close open tabs in the group.

(This was actually implemented for #215, but I apparently forgot this issue existed, so I'm just going to mark this one as a duplicate of #215.)

**Closed by josh-berry** 2022-03-18 05:04 UTC
Labels: i-enhancement
