### ISSUE TITLE
Select Multiple Tabs in Sidebar

### ISSUE THREAD

**Issue by ianelletson** [josh-berry/tab-stash#170] opened 2021-11-07 14:39 UTC
### Problem Statement

Select multiple tabs at once in the sidebar in order to perform tab stash operations across the collection

### Preferred Solution(s)

Shift-click tabs in the sidebar, then right click or other UI elements to stash (optionally to move to existing stash, or at least drag and drop)

### Alternative Solution(s)

Currently able to select from tab bar or go one-by-one

### Additional Context

Strict quality of life enhancement. Excellent, simple (in the best way) add-on. Thank you!

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2021-11-08 00:15
Hi, this is a duplicate of #57, so you can follow along there for updates.

Glad to hear you're enjoying Tab Stash, and thanks for taking the time to leave a suggestion!

**Closed by josh-berry** 2021-11-08 00:15 UTC
