### ISSUE TITLE
"Open link in new tab" context menu in sidebar doesn't work on FF 107

### ISSUE THREAD

**Issue by Andrx18** [josh-berry/tab-stash#304] opened 2022-11-22 06:27 UTC
### Question

Not sure if this is a bug or if I messed something up.

My sidebar context menu is glitchy, and opening tab from it doesn't do anything. I'm pretty sure it wasn't like this a few days ago.

![Screenshot 2022-11-21 203650](https://user-images.githubusercontent.com/118771949/203239114-94a3f5ad-3033-4134-badf-b7cf2e2e1abb.png)

It's only from the sidebar, tab is fine.

I've tried restarting firefox as the wiki suggested, and also checked the log but nothing.
Not sure what to do, it's got me all panicky lol

Thanks.
### System Details

- **OS Version:** [Windows 10]
- **Browser Version:** [Firefox 107.0]
- **Tab Stash Version:** [2.11.1]

**Comment by Ruco** [comment] 2022-11-23 14:19
Just wanted to let @josh-berry know that I have exactly the same issue as @Andrx18 

It started after I upgraded to Firefox 107

**Comment by josh-berry** [comment] 2022-11-23 21:23
I see what you mean; I just got FF 107 and I see the problem on my end, too. This seems to be a bug in Firefox itself (the context menu is added/handled by Firefox to any link, and isn't managed by Tab Stash—Tab Stash just tells Firefox "hey this is a link" and Firefox does the rest).

As a workaround, you can Ctrl+Click a tab (or Cmd+Click on Mac) to open it in the background—this action is handled by Tab Stash itself and still seems to work. It's not an exact duplicate of Firefox's behavior, but hopefully gets you close enough until Firefox can fix the issue.

Sorry for the trouble!

**Comment by josh-berry** [comment] 2022-11-23 21:24
FWIW I will open a bug against Firefox when I get a chance.

**Comment by josh-berry** [comment] 2022-11-24 03:55
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1802266

**Comment by Ruco** [comment] 2022-11-25 14:49
For anyone else. There's 2 other (temporary) workarounds.

1. Simply not using the Sidebar, but the "regular" mode/version of Tab Stash
2. In `about:config` set `screenshots.browser.component.enabled` to `true`

**Comment by rjshrjndrn** [comment] 2022-12-06 15:51
`ctrl-alt-s` is also not working. 
Mozilla Firefox 107.0

**Comment by josh-berry** [comment] 2023-01-03 02:39
This seems to be fixed in FF 108, so I'm going to close this out.

@rjshrjndrn Sounds like yours is a different issue; if it's still happening with FF 108, please open a new issue and I'd be happy to help.

**Closed by josh-berry** 2023-01-03 02:39 UTC
Labels: i-bug, upstream dependency

**Comment by rjshrjndrn** [comment] 2023-01-03 10:10
@josh-berry it's working. :tada:
