### ISSUE TITLE
Remove Duplicate Entries

### ISSUE THREAD

**Issue by Lightaesir** [josh-berry/tab-stash#318] opened 2023-01-04 15:22 UTC
### Problem Statement
To avoid clutter and too many redundant entries

### Preferred Solution(s)
Option, to be asked or as in onetab block duplicates before saving a tab group

### Alternative Solution(s)

I don't know

### Additional Context

nothing

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2023-01-05 01:28
I'm a little unclear on what you're asking for here—Tab Stash will already prevent you from saving duplicates to the same group, though it is possible if you explicitly try—e.g. if you already have duplicate tabs open and try to stash them all in one go.

If you're looking for a more general way to de-duplicate your entire stash, there are other addons that can do this for you and work quite well with Tab Stash (for example, https://addons.mozilla.org/en-US/firefox/addon/bookmarks-clean-up/ ).

Can you elaborate a little more on what you're looking for?

**Comment by seanbuckley** [comment] 2023-02-07 16:36
I'd also love to see this. I envision something similar to [OneTab](https://www.one-tab.com/)'s option to“silently reject/discard all duplicate tabs” (when a save action occurs). That deduplication happens in an overall manner, not just per group. If the link already exists, it's just not saved/stashed again. The intent is to avoid seeing the same link scattered around in multiple places.

**Comment by josh-berry** [comment] 2023-02-21 05:31
For the sake of keeping things organized (and because I never heard back from the OP), I'm going to mark this as a duplicate of #334. (#334 is technically a dup of this, since this one came first, but #334 has a clearer explanation of the desired feature.) If there's anything that's missing from the discussion on #334, please feel free to leave a comment there!

**Closed by josh-berry** 2023-02-21 05:31 UTC
