### ISSUE TITLE
option to hide all tabs that have been stashed

### ISSUE THREAD

**Issue by cognitiaclaeves** [josh-berry/tab-stash#316] opened 2023-01-02 16:06 UTC
### Problem Statement

I'm autistic, with ADHD. So I'm always looking for ways to only keep just enough in-sight that I need to stay focused. It's a delicate balancing act. I was unable to find an easy way to operationally clear the workspace of 'handled' (stashed) tabs without closing tabs. I only want to close tabs when I want them closed. Open and closed tabs have different impressions in my brain. Closing all stashed tabs feels destructive. I might be able to "get over" this, but "getting over" things seems to clutter the stack I have to work with of limited executive function.

### Preferred Solution(s)

Some way to hide stashed tabs. I noticed that there is no option to close all stashed tabs per group, and I can see wanting to use it this way. So my preferred solution would be the capability to hide all stashed tabs per group. This would allow me to open groups as I need to work on them, and then hide them when I'm done with them. I've been using auto-tab-discard for some time, so I'm very comfortable with letting that extension (and the similar logic that looks to be built into tab-stash) to manage memory for open tabs.

## Additional Context

There may be no difference between closing a tab and having one open and discarded from memory. The server serving the page may treat a newly opened tab as the same as an open tab that is refreshed. Or a newly opened tab might have been used in a way that caused additional arguments to be populated in the URL, so reopening may not have the same effect. I'm not sure how tab-stash would handle this, but this is an example of something that might nag at me as I'm determining if I want to close a tab or not.

On the other hand, the way a server handles timing out will not change regardless of what the client does. So no issues come up for me when I consider why I might not want to keep a tab 'open' past a server expiration.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2023-01-17 04:45
Thanks for the thoughtful feature request. Sorry it's taken me a bit of time to get back to you—there's been a lot going on in life, and I wanted to properly digest what you wrote. Now that I have, here are a few thoughts.

First, the Tab Stash UI admittedly over-simplifies this, but the various "close all..." buttons under "Unstashed Tabs" / "Open Tabs" will actually hide stashed tabs instead of closing them, so they're still there in the background should you need them again. (Though if you explicitly close an individual tab, it's closed-for-real—I just now noticed this and I should probably fix it so the behavior is consistent.) What actually happens when you click one of the "Close all..." buttons is governed by the same settings that govern the behavior when a tab is stashed.

Second, it sounds like what you are asking for is akin to #284, except for hiding instead of closing (or, similarly, following the settings that tell Tab Stash what to do when stashing tabs). If something like "#284 with hiding" were implemented, would that do what you need?

Finally, regarding the additional context, visible/hidden and loaded/discarded are all distinct states—so yes, closing a tab gets rid of it entirely, but if a tab is open, it could be in any combination of visible/hidden + loaded/discarded states. All that said, webpages are complex beasts, and there could be information that is lost when a tab is discarded and/or closed (but not when it's hidden). For example, you could be in the middle of writing a GitHub comment, the tab could get discarded (or you could accidentally hit "Refresh") and your half-written comment would be gone. ;)

Tab Stash will save only the URL of the page at the time it was stashed. If you enter some info on the page, Tab Stash doesn't know about it and can't save it. If you navigate to a different page, Tab Stash will treat the new page as different from what is saved in the stash, even though it's loaded in the same tab (i.e. it sees it as a tab that isn't stashed at all).

Hope this helps; let me know your thoughts, and if something like "#284 with hiding" would work for you?

**Comment by olliebean** [comment] 2023-01-17 11:33
Just to add to this, I was unaware that the "Close all..." buttons hide, rather than close, stashed tabs, and this makes "Close all stashed tabs" very useful to quickly clear some space on the tab bar. It would be good to have this functionality per stash, which does seem to be "#284 with hiding". I wonder, also, if the "Close all stashed tabs" function in the "Unstashed Tabs" section could be given a keyboard shortcut?

**Comment by josh-berry** [comment] 2023-02-19 19:22
I'm going to go ahead and mark this as a duplicate of #284, which is now queued up for the next release.

@olliebean Yes, I think a keyboard shortcut is possible. I haven't put a lot of attention on keyboard shortcuts/navigation so far, but #131 might be relevant to what you're asking (navigation within the Tab Stash UI), or feel free to open another feature request if you're thinking of something different!

**Closed by josh-berry** 2023-02-19 19:22 UTC
