### ISSUE TITLE
make `delete this group` safer to use.

### ISSUE THREAD

**Issue by gapplef** [josh-berry/tab-stash#73] opened 2020-06-26 13:55 UTC
### Problem Statement

If  my understand is correct, with current Tab Stash,  `delete this group` would delete a group of tabs without any warning or any way to undo the action. And also no option to change this behavior.

The icon of  `delete this group` is just beside the `restore`(open tabs) icons, and can be easily triggered by accident, and there is no way to get back these lost tabs. I think this is really danger and a bad design.

### Preferred Solution(s)

- move  `delete this group` to right click menu or hidden under a hamburger / three dots menu.
- pop-up a warning before delete tab group, and let user to confirm or withdraw their action.
- provide a way to undo the action after delete a tab group.

### Alternative Solution(s)

- option to hidden `delete this group`

### Additional Context

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2020-06-26 16:24
Hi, thanks for filing this—it's actually a duplicate of #20, so please feel free to leave any additional thoughts/comments there.

**Closed by josh-berry** 2020-06-26 16:24 UTC
Labels: enhancement, r:duplicate
