### ISSUE TITLE
Display "Clear" (X) button in search field when non-empty

### ISSUE THREAD

**Issue by pm64** [josh-berry/tab-stash#114] opened 2021-03-11 17:47 UTC
### Problem Statement
The search field is frequently used to locate stashed tabs. Once that feature has been used, multiple interactions are necessary to restore the UI to its initial state (i.e. selection and deletion of search text).

### Preferred Solution(s)
A "Clear" button (normally labeled "X") within the search field, visible only when the search field is non-empty, is a common and effective remedy for this annoyance.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2021-03-11 21:27
Hi, thanks for your comment! I agree this would be useful and it's one of the polish items that I haven't had a chance to get to yet.

In the meantime, if you're not already aware, you can clear the search field by hitting "Esc" on your keyboard while the field is selected, which is a little more convenient than selecting/deleting text. Hope this helps!

**Comment by josh-berry** [comment] 2023-03-05 19:02
Somehow I missed that #299 was a duplicate of this, and the "clear" button actually got added in the last release (2.12). I'll go ahead and close this, my bad!

**Closed by josh-berry** 2023-03-05 19:02 UTC
Labels: i-polish
