### ISSUE TITLE
Import appends to fresh created stash and on interrupt delete other URLs

### ISSUE THREAD

**Issue by psydvl** [josh-berry/tab-stash#190] opened 2021-12-28 05:19 UTC
### System Details

- **OS Version:** [e.g. Windows 10, or Ubuntu 18.04]
- **Browser Version:** Firefox 95.0.2
- **Tab Stash Version:** 2.10.1

<details>
<summary><b>Installed Browser Extensions:</b></summary>

- uBlock Origin
- AdGuard AdBlocker
- Dark Reader
- HTTPS Everywhere
- Search by Image
- Grammar and Spell Checker - LanguageTool
- OneTab
- ClearURLs
- Image Search Options
- Web Archives
- Facebook Container
- Grammarly for Firefox
- Russian (RU) Language Pack
- Russian spellchecking dictionary
- Firefox Multi-Account Containers
- Reddit Enhancement Suite
- GNOME Shell integration
- Wappalyzer
- Violentmonkey
- KeePassXC-Browser
- Privacy Pass
- Unpaywall
- SteamDB
- Wayback Machine
- Octotree - GitHub code tree
- Runet Censorship Bypass
- The Stream Detector
- Refined GitHub
- Tab2QR
- Extension source viewer
- Toby For Tabs
- Tab Stash
- Imagus

</details>

### Describe the Bug
1) When you start importing, it's appending to fresh created stash instead of creating new one.
2) When you interrupt import started which appending to fresh created stash (like from stashing before)

### Expected Behavior
1) Creating new group(stash) for import ignored new tab appending option (seen in advanced settings).
2) Only newly preimported URLs deleted if appending is feature, nor bug

### Steps to Reproduce

1. Create new group
2. Start importing procedure (e.g. from OneTab)
3. Interrupt import using <kbd>Cancel</kbd> button
4. See all tabs from new group deleted 😥

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2021-12-28 18:11
I'm not sure I completely follow what you're asking, but if I understand correctly:
* You were expecting import to append to an existing unnamed stash (if it was recently-created) rather than creating a new one.
* You were expecting cancelling the import to leave the partially-imported tabs around instead of deleting them.

Both of these behaviors are actually by design.

Importing always creates new stashes, for two reasons. First, most of the time when someone is importing something, they probably want to sort through and organize it afterwards, so we always try to keep newly-imported tabs separate from everything that was already there. Second, importing can (and by default, will) create multiple stashes if it finds appropriate dividers, section headers, etc. during the import--this would not be possible if import were limited to appending to an existing stash.

You can easily work around this by selecting and moving the imported tabs to your desired group. Click on the icon of the first tab, then shift-click the last tab to select them all, and move them wherever you want them to go. Note that Shift+Click only works within the same group, however, so you'll have to repeat the Click/Shift+Click for each imported group, or turn off the grouping option during the import so everything goes into one group.

As for cancellation, we clean up tabs from a half-completed import because we always want to leave the user's stash in a good state--either everything is imported, or nothing is there. This makes it easy for the user to try again if an import went poorly; they can stop it in the middle, fix whatever the problem was, and give it another try without having to do any manual cleanup or trying to remember what was just imported and what was already there.

Hope this clarifies things! Did I understand your original issue correctly or is there anything I missed?

**Comment by psydvl** [comment] 2021-12-29 04:14
Not at all
Sorry about bad explanation.
I'll try it again:

### Bug Explanation:
1. For now, import appends to an existing unnamed stash (if it was recently-created)
2. For now, when import appending to existing unnamed stash, and you abort it, that existing unnamed stash will be completely removed (with tabs existed before import).

### Steps to reproduce <sub>(just checked from clean Firefox 95.0.2 profile)</sub>
1. Open any tab and stash it to new stash
2. Import any URLs list (in any import mode) -> It will be added to previous step stash
3. If URLs list big enough(and import not too fast), you can cancel import -> Stash from first step will be erased with import AND tab from first step

**Comment by josh-berry** [comment] 2021-12-31 19:57
Aha, thanks for clarifying, that helped a lot! I see exactly what you mean. Yes, this is very much a bug, and I'll see what I can do to fix it in the next release. Sorry for the trouble and thanks for reporting it!

**Comment by josh-berry** [comment] 2021-12-31 21:11
(Possibly related to, or has the same root cause as, #179)

**Comment by josh-berry** [comment] 2022-01-17 02:08
The fix will be in the next release!

**Closed by josh-berry** 2022-01-17 02:08 UTC
Labels: i-bug
