### ISSUE TITLE
Option on what to do with tab by single mouse click anywhere on it.

### ISSUE THREAD

**Issue by RealRedFox** [josh-berry/tab-stash#182] opened 2021-12-03 09:14 UTC
### Problem Statement
Now it is possible to open stashed tab in new tab in browser with single click anywhere on stashed tab, in this case stashed tab remains in stash. Or I can open it in new browser tab and remove from stash by clicking special icon on the right side of stashed tab.

### Preferred Solution(s)
As I think it can be useful, if user can change what action should Tab Stash will make on single click anywhere on the stashed tab - 1) open in new browser tab and keep it in stash, 2) open in new browser tab and remove it from stash.

Thanks in advance.

<hr>
<em>Readers: If you are also interested in seeing this feature be developed, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the feature request, but "Me too!" comments are not counted by the voting system.</em>

**Comment by josh-berry** [comment] 2021-12-04 19:03
Got it. Thanks for the feature request, I'll keep it in mind for a future release!

**Comment by josh-berry** [comment] 2024-07-14 22:12
Oops, this is actually a duplicate of:

- #135 

My bad; I should have noticed this earlier.

**Closed by josh-berry** 2024-07-14 22:12 UTC
Labels: i-enhancement
